[package]
name = "toolkit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
urlencoding = "2.1.0"
html-escape = "0.2.11"
unescape = "0.1.0"
ipnet = "2.5.0"
chrono = "0.4"
